--- 
apiVersion: v1
kind: Service
metadata: 
  name: mufghelloworld
  namespace: mufg
  labels:
    app: mufghelloworld
spec: 
  ports: 
    - 
      name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector: 
    app: mufghelloworld
  type: LoadBalancer


---


apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mufghelloworld-deployment
  namespace: mufg
  labels:
    app: mufghelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mufghelloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mufghelloworld
    spec:
      containers:
      - name: mufghelloworld
        image: mufgpoc/mufghelloworld
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
      imagePullSecrets:
      - name: dockerregistrysecret
